name: PyBirds  # Name of your conda environment
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults 

dependencies:
  # - hdf5==1.12.1
  # - matplotlib==3.9.2
  # - numpy==1.26.4
  # - opencv==4.10.0
  # - pandas==2.2.2
  # - pillow==10.4.0
  # - pip==24.2
  - python==3.12.7
  - pytorch
  - gunicorn
  - flask
  # - pytorch-cuda==11.8
  # - scikit-image==0.24.0
  # - scikit-learn==1.5.1
  # - scipy==1.13.1
  # - seaborn==0.13.2
  # - torchaudio==2.5.1
  # - torchtriton==3.1.0
  # - torchvision==0.20.1
  # - tqdm==4.66.5