name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      IMAGE_TAG: pybirds-server:latest
      TIMESTAMP: ${{ github.run_id }}
      
    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Log in to Docker Hub using the access token
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pybirds-server:${{ env.TIMESTAMP }}

    # Tag and push the Docker image to Docker Hub
    - name: Tag and Push Docker image
      run: |
        docker tag pybirds-server:${{ env.TIMESTAMP }} ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }}
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }}
