name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Log in to Docker Hub using the access token
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pybirds-server:$(date +%s)

    # Tag and push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        IMAGE_TAG=pybirds-server:latest
        docker tag pybirds-server:$(date +%s) ${{ secrets.DOCKER_USERNAME }}/$IMAGE_TAG
        docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_TAG
